import { Paperclip, Terminal, FileText, FastForward } from 'lucide-react';

export default function AttackStoryReconstruction({ data }) {
  const narrative = data.narrativeEntries || [];
  const rawLogStream = data.rawLogStream || [];

  return (
    <div
      className="reconstruction-layout"
      style={{ display: 'flex', height: '100%', gap: 'var(--space-4)', padding: 'var(--space-4)', flexWrap: 'nowrap' }}
    >
      {/* ── Left Pane: Raw Log Stream ── */}
      <div style={{
        flex: 1,
        display: 'flex',
        flexDirection: 'column',
        background: '#0f172a',
        borderRadius: 'var(--radius-lg)',
        overflow: 'hidden',
        minWidth: 0,
        minHeight: 300,
      }}>
        <div style={{
          padding: 'var(--space-3) var(--space-4)',
          borderBottom: '1px solid #1e293b',
          display: 'flex',
          alignItems: 'center',
          gap: 8,
          color: '#94a3b8',
          flexShrink: 0,
        }}>
          <Terminal size={15} />
          <span style={{ fontSize: 12, fontWeight: 600 }}>Raw Log Stream (SIEM/EDR)</span>
          <FastForward size={13} style={{ marginLeft: 'auto', color: '#10b981' }} />
        </div>

        <div style={{
          flex: 1,
          overflowY: 'auto',
          padding: 'var(--space-4)',
          fontFamily: 'var(--font-mono)',
          fontSize: 10.5,
          color: '#cbd5e1',
          lineHeight: 1.8,
        }}>
          {rawLogStream.length > 0 ? (
            rawLogStream.map((entry, i) => (
              <div key={i} style={{ color: entry.color }}>
                {entry.text}
              </div>
            ))
          ) : (
            <>
              <div style={{ color: '#3b82f6' }}>[SYSTEM] Correlation Engine initializing...</div>
              <div style={{ color: '#94a3b8' }}>[SYSTEM] No raw log stream configured for this scenario.</div>
            </>
          )}
        </div>
      </div>

      {/* ── Right Pane: Attack Story ── */}
      <div style={{
        flex: 1.4,
        display: 'flex',
        flexDirection: 'column',
        background: 'var(--bg-secondary)',
        borderRadius: 'var(--radius-lg)',
        border: '1px solid var(--surface-border)',
        overflow: 'hidden',
        minWidth: 0,
        minHeight: 300,
      }}>
        <div style={{
          padding: 'var(--space-3) var(--space-4)',
          borderBottom: '1px solid var(--surface-border)',
          display: 'flex',
          alignItems: 'center',
          gap: 8,
          flexShrink: 0,
          background: 'var(--bg-secondary)',
        }}>
          <FileText size={15} color="var(--accent-primary)" />
          <span style={{ fontSize: 12, fontWeight: 600 }}>Grounded Attack Story (LLM Output)</span>
        </div>

        <div style={{ flex: 1, padding: 'var(--space-4) var(--space-6)', overflowY: 'auto' }}>

          {/* Methodology banner */}
          <div style={{
            background: 'var(--accent-light)',
            padding: 'var(--space-3) var(--space-4)',
            borderRadius: 'var(--radius-md)',
            marginBottom: 'var(--space-4)',
            borderLeft: '4px solid var(--accent-primary)',
          }}>
            <h4 style={{ fontSize: 11, fontWeight: 700, color: 'var(--accent-primary)', marginBottom: 4, textTransform: 'uppercase' }}>
              Methodology
            </h4>
            <p style={{ fontSize: 11, color: 'var(--text-secondary)', lineHeight: 1.6 }}>
              This narrative is generated by a local LLM grounded by the Correlation Engine.{' '}
              <strong>Every [CONFIRMED] claim is backed by a specific log citation</strong> extracted from the evidence graph — preventing hallucinations.
            </p>
          </div>

          {narrative.length > 0 ? (
            narrative.map((entry, i) => (
              <div key={i} className={`narrative-entry ${entry.type}`}>
                <div className={`narrative-tag ${entry.type}`}>
                  {entry.type === 'confirmed' ? '✓ CONFIRMED'
                    : entry.type === 'predicted' ? '⚡ PREDICTED'
                    : '🎯 ACTION REQUIRED'}
                </div>
                <div style={{ fontSize: 'var(--text-xs)', color: 'var(--text-tertiary)', marginBottom: 4, fontFamily: 'var(--font-mono)' }}>
                  {entry.timestamp}
                </div>
                <div className="narrative-text">{entry.text}</div>
                {entry.evidence && (
                  <div className="narrative-evidence">
                    <Paperclip size={11} style={{ flexShrink: 0 }} />
                    <span style={{ overflow: 'hidden', textOverflow: 'ellipsis', whiteSpace: 'nowrap' }}>
                      {entry.evidence}
                    </span>
                  </div>
                )}
              </div>
            ))
          ) : (
            <div style={{ color: 'var(--text-tertiary)', fontSize: 13, textAlign: 'center', marginTop: 'var(--space-8)' }}>
              No narrative entries for this scenario
            </div>
          )}
        </div>
      </div>
    </div>
  );
}
